project:
  type: website
  output-dir: _site

website:
  title: "syncweaver"
  site-url: https://ccbr.github.io/syncweaver
  repo-url: https://github.com/CCBR/syncweaver
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  page-navigation: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Docs
        menu:
          - text: Introduction
            href: guide/index.qmd
          - text: Command-line interface
            href: cli/index.qmd
          - text: Python API
            href: reference/index.qmd
      - text: About
        menu:
          - text: Citation
            href: cite.qmd
          - text: Contributing
            href: CONTRIBUTING.md
          - href: contributors.qmd
          - text: License
            href: LICENSE.md
          - text: Changelog
            href: CHANGELOG.md

  page-footer:
    background: black
    foreground: white
    left: |
      Created by the
      [CCR Collaborative Bioinformatics Resource](https://github.com/CCBR)

quartodoc:
  style: pkgdown
  package: syncweaver
  sidebar: _sidebar.yml
  parser: google
  sections:
    - title: Modules
      contents:
        - git
        - lockfile
        - patch
        - util
    - title: CLI commands
      desc: Command-line interface
      contents:
        - cli.main
        - cli.add
        - cli.patch
        - cli.templates
    - title: Templates
      desc: Template files
      contents:
        - templates

metadata-files:
  - _sidebar.yml
  - _cli-sidebar.yml

filters:
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/

execute:
  freeze: auto
  eval: true
  echo: true

format:
  fnl-html:
    code-fold: show
