name: auto-format

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-format:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.CCBR_BOT_APP_ID }}
          private-key: ${{ secrets.CCBR_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: git config
        run: |
          git config --global user.name "CCBR-bot"
          git config --global user.email "258092125+ccbr-bot@users.noreply.github.com"
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

      - name: format
        uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - name: commit & push
        run: |
          git add .
          git commit -m "ci: 🤖 auto-format" || echo "nothing to commit"
          git push || echo "nothing to push"
