name: post-release

on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: CCBR/actions/post-release@main
        with:
          github-token: ${{ github.token }}
          update-sliding-tags: true
